### ISSUE TITLE
Connection timed out (output-sqlserver; 0.5.1)

### ISSUE THREAD

**Issue by yjcet** [embulk/embulk-output-jdbc#104]
> Error: java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: ホスト ss2016、名前付きインスタンス mssqlserver への接続が失敗しました。エラー: "java.net.SocketTimeoutException: Receive timed out"。サーバーとインスタンスの名前を調べ、ポート 1434 への UDP トラフィック がファイアウォールにブロックされていないことを確認してください。SQL Server 2005 以降では、SQL Server Browser サービスがホスト上で実行されている ことを確認してください。

I don't open UDP/1434. On the contrary, I don't boot SQL Server Browser service.
If I specify the port for SQL Server engine, "Browser Service" is not required, is it?
it is thankful to be able to use not the same as 0.5.0 also in the previous environment.

... I am not good at English.

**Comment by hito4t** [comment]
Did you specify `instance`?
If both `instance` and `port` are specified, `port` is ignored.

https://msdn.microsoft.com/ja-jp/library/ms378428%28v=sql.110%29.aspx
https://msdn.microsoft.com/en-us/library/ms378428%28v=sql.110%29.aspx

This is a specification of SQL Server JDBC Driver, but a bit confusing.

I'll modify as follows.
- If both `instance` and `port` are specified, error.
- If neither  `instance` nor `port` are specified, port 1433 is used.

**Comment by yjcet** [comment]
Thank you for your reply.
> Did you specify instance?
Yes. It is untested, but I found a mechanism.

I think it's better "If both a portNumber and instanceName are used, the portNumber will take precedence and the instanceName will be ignored" as note at
https://msdn.microsoft.com/en-us/library/ms378428%28v=sql.110%29.aspx
Neither ignore port nor treat as error.

But, It's up to you. Thank you.

**Comment by yjcet** [comment]
Test was successful. Problem has gone if not specify instance. Thank you.
