### ISSUE TITLE
Suggestion: Option to control how merge_direct updates existing rows

### ISSUE THREAD

**Issue by tomykaira** [embulk/embulk-output-jdbc#110]
When using `merge_direct` on MySQL, there are cases that some columns must not be updated, or must be updated conditionally.
I implemented an option to manually specify `ON DUPLICATE KEY UPDATE` clause [patch](https://github.com/tomykaira/embulk-output-jdbc/commit/9e92858a7a9bf7ce32dcd9af1765fbed5c1da5bc). This option gives full control of how to update.

The drawback is that this option cannot cover other RDBMSs like PostgreSQL.
I appreciate if my change is merged, but I am afraid that such a method is not suitable for this project.
Let me know the opinion of maintainers. Thanks!

**Comment by hito4t** [comment]
Hi!

Thank you for useful suggestion!

Ideally, all features work in the same way for all RDMSs.
But we should use RDBMS specific features for high performance, because standard SQLs are not enough for bulk loading.

`ON DUPLICATE KEY UPDATE` may be MySQL specific SQL, but we may be able to implement the same feature for other RDBMSs.
(We may be able to add properties which can generate `ON DUPLICATE KEY UPDATE` clause, instead of `ON DUPLICATE KEY UPDATE` clause itself.)

Would you show me sample YMLs for `ON DUPLICATE KEY UPDATE`?

Thanks.

**Comment by tomykaira** [comment]
I am happy with your response!

Here is my goal:

```
out:
  type: mysql
  table: A
  ...
  mode: merge_direct
  on_duplicate_key_update: |
    name       = IF(updated_at > VALUES(updated_at), name, VALUES(name)),
    updated_at = IF(updated_at > VALUES(updated_at), updated_at, UTC_TIMESTAMP())
```

I want to update column `A.name` by the result of joining `A` with another table `B`.
`A` is receiving new data while embulk runs, so I want to overwrite a row only if it is not updated.

As far as I think, in order to provide enough flexibility for all RDMSs, a small language will be required.

**Comment by hito4t** [comment]
Thank you for your reply!

I've researched SQL for merging in each RDBMSs.
Almost all of them can support `on_duplicate_key_update` property.
If the `on_duplicate_key_update` clause uses only standard SQL, they'll work in the same way.

PostgreSQL
<pre>
with updated as (
  update A set
    value1 = B.value1,   -- replaced with on_duplicate_key_update
    value2 = B.value2    -- replaced with on_duplicate_key_update
  from B
  where A.id = B.id
  returning B.id
)
insert into A (
  id,
  value1,
  value2
)
select * from B
where not exists
  (select 1 from updated
   where B.id = updated.id);`
</pre>

Oracle & SQL Server (not support `merge` mode yet)
<pre>
MERGE INTO A USING B
  ON (A.ID = B.ID)
  WHEN MATCHED THEN
    UPDATE SET
      VALUE1 = B.VALUE1,   -- replaced with on_duplicate_key_update
      VALUE2 = B.VALUE2    -- replaced with on_duplicate_key_update
  WHEN NOT MATCHED THEN
    INSERT (
      ID,
      VALUE1,
      VALUE2
    ) VALUES (
      B.ID,
      B.VALUE1,
      B.VALUE2
    );
</pre>

Redshift cannot support now.

**Comment by tomykaira** [comment]
Thank you so much for researching and sorry for late response.
It is good news.

There will be two choices.

1. Define `on_duplicate_key_update` as string of standard SQL as I did.
2. Define `on_duplicate_key_update` as map of column name -> value definition SQL.

IMO, option 1 will be better because it is more flexible.
Is there anxiety?

**Comment by hito4t** [comment]
I agree with you.
1 is better.
