### ISSUE TITLE
SSL value always true 

### ISSUE THREAD

**Issue by AntoineAugusti** [embulk/embulk-output-jdbc#118]
Following the merge of https://github.com/embulk/embulk-output-jdbc/pull/117 and the release of 0.6.2, my PR seems to be faulty.

It seems that the SSL value of the enum is always set to `verify`, leading to the property `ssl=true` in the connection string.

I can't manage to debug this as the command `embulk run -L /Users/antoine/Documents/embulk-output-jdbc/embulk-output-redshift/build template.yml.liquid` complains about a missing gemspec file.

I think that this value (https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-redshift/src/main/java/org/embulk/output/RedshiftOutputPlugin.java#L70) should be `"\"disable\""`, but it doesn't explain why the value seems to be set to verify everytime. The mapping between a string in the configuration file and the Ssl enum seems to doesn't work as putting `ssl: foo` doesn't throw an exception.

Any help would be appreciated as the latest released version is currently breaking if people did not import the Redshift certificate manually as it tries to verify it

**Comment by hiroyuki-sato** [comment]
@AntoineAugusti This is off topic.

Could you try ``-I`` option instead of ``-L``.
``-L`` option does not work properly on 0.8.12 (Now fixed on master)
https://github.com/embulk/embulk/issues/457


```
cd  embulk-output-jdbc
./gradlew classpath
embulk run -I embulk-output-redshift/lib config.yml
```

**Comment by AntoineAugusti** [comment]
Thanks. I've submitted a fix in https://github.com/embulk/embulk-output-jdbc/pull/119.

Your list of commands works as expected. Should I send a PR to fix the README here or wait for the latest version of Embulk to be released?
