### ISSUE TITLE
Redshift output doesn't support region parameter

### ISSUE THREAD

**Issue by sash-ko** [embulk/embulk-output-jdbc#126]
It not possible to Redshift output in "eu-central-1" due to missing **region** parameter in COPY command

**Comment by hito4t** [comment]
Thank you for adding the issue!

It seems that we should specify region of S3 bucket in COPY command if it is different from region of Redshift.

I'll fix it.

**Comment by hito4t** [comment]
I've created PR for this issue.
https://github.com/embulk/embulk-output-jdbc/pull/128

embulk-output-redshift specifies region by S3 bucket name, so we don't need to specify region in yml.
(IAM user needs `s3:GetBucketLocation` permission.)
