### ISSUE TITLE
Cannot handle composite keys

### ISSUE THREAD

**Issue by dallin** [embulk/embulk-output-jdbc#149]
I've been playing around with embulk for a couple hours trying to merge data from a SQL Server DB with a composite primary key (4 columns), but there doesn't seem to be a way to do this. I would be able to work around this except that the table in question does not have a column with the UNIQUE property set (not my design; it is Microsoft Dynamics).

**Comment by hito4t** [comment]
Hi
I've implemented `merge` mode for SQL Server.
https://github.com/embulk/embulk-output-jdbc/pull/151

This mode will update the output table by input record if the same key exists, and will insert input record into the target table otherwise.
Does this help?

**Comment by dallin** [comment]
Yes, this works actually. If I create the destination tables prior to running the script it works flawlessly. Thank you!

**Comment by hito4t** [comment]
I've merged #151 and released!
