### ISSUE TITLE
How can i update data into Oracle?

### ISSUE THREAD

**Issue by mrmanhluc** [embulk/embulk-output-jdbc#163]
Please tell me how can i update data into Oracle? I don't see any option to update data into Oracle, just insert data into oracle!

**Comment by hito4t** [comment]
Hi
embulk-output-xxxxs have `merge` / `merge_direct` mode for updating records, but unfortunately embulk-output-oracle doesn't support the mode yet.
I'll implement the mode.

**Comment by mrmanhluc** [comment]
Hi hito4t

Thanks so much for your answer!

**Comment by hito4t** [comment]
I've created the PR #165 .
