### ISSUE TITLE
[Feature request] load temporary data into another schema/db. 

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-output-jdbc#164]
Some users(include me) want to load data into the target database with the following scenario. 

* First, load data into another schema or database once.
* After that, load data into target data.

This request is a feature request for another tool integration. 
For example, The [ridgepole](https://github.com/winebarrel/ridgepole).

This tool has own configuration schema for a database. 
When this tool executes, all of the tables which are not include in the configuration file will drop.

The embulk-output-jdbc create a temporary table on the same schema/db. 
It's inconvenient for that tool. 

## Reference

[Twitter](https://twitter.com/toyama0919/status/842608691211718656) Japanese text

**Comment by hiroyuki-sato** [comment]
Same issue. 
[Twitter](https://twitter.com/yokotty_j/status/867213594617815040) (Japanese text)

A user wants to use the ridgepole with embulk-output-redshift.

**Comment by hito4t** [comment]
I've created the PR #177 .

**Comment by hiroyuki-sato** [comment]
0.7.9 Added this feature.
