### ISSUE TITLE
embulk-output-redshift: Getting an error when using uppercase letters in table name in yml

### ISSUE THREAD

**Issue by xaduha** [embulk/embulk-output-jdbc#168]
"Optional.get() cannot be called on an absent value"

**Comment by hiroyuki-sato** [comment]
Hello, @xaduha 

Can you give us more detail about your issue?

* embulk version 
* plugin version
* Stack trace error.
* config.yml
* sample data
* DDL info

It may be helpful for help this issue.

**Comment by xaduha** [comment]
1. embulk version: tried 0.8.17 and 0.8.18

2. plugin version: this probably embulk-output-redshift-0.7.7 or latest

3. stacktrace: https://gist.github.com/xaduha/97d230d25ad9b06216aecfddb223b728

4. config: https://gist.github.com/xaduha/082777ca8984e78649a1163654830a7f

5. data from: https://www.kaggle.com/wendykan/lending-club-loan-data

6. DDL info: don't know what to put here, nothing special was used.

**Comment by hiroyuki-sato** [comment]
@xaduha 
Thank you for sharing information.

I've never seen that error.

About the subject ` Getting an error when using uppercase letters in table name in yml`

Can you load data into Reshift if the table is lowercase? (ex. loan2).
I'm not familiar about Reshift. 
It seems that the Reshift case-insensitive
http://docs.aws.amazon.com/redshift/latest/dg/r_names.html

If the data load correctly with a lowercase table name, embulk-output-redshift should output a warning if table name uses uppercase.

Can you try it?

Best regards.

**Comment by hito4t** [comment]
@xaduha @hiroyuki-sato 
Thank you for sharing issue!
I could reproduce the error.

Redshift may create table name in lowercase even if enclosed by double quotations (ex. `create table "Loan") unlike other RDBMSs.
So embulk-output-redshift can't get metadata of the table and throws exception.

This is a bug and I will fix it as soon as possible.

**Comment by hito4t** [comment]
http://docs.aws.amazon.com/redshift/latest/dg/r_names.html
<pre>
identifiers are case-insensitive and are folded to lower case. 
</pre>

**Comment by hito4t** [comment]
> This is a bug and I will fix it as soon as possible.

I've created #170 .

**Comment by xaduha** [comment]
@hiroyuki-sato it works as expected when table name doesn't contain uppercase letters.

@hito4t thanks!

**Comment by hiroyuki-sato** [comment]
@xaduha That's great!.
@hito4t Thanks!
