### ISSUE TITLE
The constructor of `org.embulk.spi.time.TimestampFormatter` has been deprecated in  Embulk 0.8.29.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-output-jdbc#190]
The constructor of `org.embulk.spi.time.TimestampFormatter` has been deprecated in  Embulk 0.8.29.

```
[WARN] A plugin uses a deprecated constructor of org.embulk.spi.time.TimestampFormatter.
[WARN] Please tell the plugin developer to stop using the constructor, or report this to:
[WARN] https://github.com/embulk/embulk/issues/745
[WARN] java.lang.Thread.getStackTrace(Thread.java:1556)
[WARN] org.embulk.spi.time.TimestampFormatter.<init>(TimestampFormatter.java:91)
[WARN] org.embulk.output.jdbc.setter.ColumnSetterFactory.newTimestampFormatter(ColumnSetterFactory.java:78)
[WARN] org.embulk.output.jdbc.setter.ColumnSetterFactory.newCoalesceColumnSetter(ColumnSetterFactory.java:132)
[WARN] org.embulk.output.postgresql.setter.PostgreSQLColumnSetterFactory.newCoalesceColumnSetter(PostgreSQLColumnSetterFactory.java:26)
[WARN] org.embulk.output.jdbc.setter.ColumnSetterFactory.newColumnSetter(ColumnSetterFactory.java:38)
[WARN] org.embulk.output.jdbc.AbstractJdbcOutputPlugin.newColumnSetters(AbstractJdbcOutputPlugin.java:727)
[WARN] org.embulk.output.jdbc.AbstractJdbcOutputPlugin.open(AbstractJdbcOutputPlugin.java:952)
[WARN] org.embulk.spi.util.Executors.process(Executors.java:55)
[WARN] org.embulk.spi.util.Executors.process(Executors.java:42)
[WARN] org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:184)
[WARN] org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:180)
[WARN] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[WARN] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[WARN] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[WARN] java.lang.Thread.run(Thread.java:745)
2017-08-04 11:43:36.383 +0900 [INFO] (0019:task-0027): Loading 8 rows (847 bytes)
[WARN] A plugin uses a deprecated constructor of org.embulk.spi.time.TimestampFormatter.
[WARN] Please tell the plugin developer to stop using the constructor, or report this to:
[WARN] https://github.com/embulk/embulk/issues/745
[WARN] java.lang.Thread.getStackTrace(Thread.java:1556)
[WARN] org.embulk.spi.time.TimestampFormatter.<init>(TimestampFormatter.java:91)
[WARN] org.embulk.output.jdbc.setter.ColumnSetterFactory.newTimestampFormatter(ColumnSetterFactory.java:78)
[WARN] org.embulk.output.jdbc.setter.ColumnSetterFactory.newCoalesceColumnSetter(ColumnSetterFactory.java:132)
[WARN] org.embulk.output.postgresql.setter.PostgreSQLColumnSetterFactory.newCoalesceColumnSetter(PostgreSQLColumnSetterFactory.java:26)
[WARN] org.embulk.output.jdbc.setter.ColumnSetterFactory.newColumnSetter(ColumnSetterFactory.java:38)
[WARN] org.embulk.output.jdbc.AbstractJdbcOutputPlugin.newColumnSetters(AbstractJdbcOutputPlugin.java:727)
[WARN] org.embulk.output.jdbc.AbstractJdbcOutputPlugin.open(AbstractJdbcOutputPlugin.java:952)
[WARN] org.embulk.spi.util.Executors.process(Executors.java:55)
[WARN] org.embulk.spi.util.Executors.process(Executors.java:42)
[WARN] org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:184)
[WARN] org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:180)
[WARN] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[WARN] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[WARN] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[WARN] java.lang.Thread.run(Thread.java:745)
```

**Comment by dmikurube** [comment]
The same as https://github.com/embulk/embulk-input-jdbc/issues/118, my ideas are to:

1. Ignore the deprecation warnings for a while. They're just "deprecated" for the time being. Removing them would be after a long interval.

OR

2. Call `TimestampFormatter(Task task, Optional<? extends TimestampColumnOption> columnOption)` instead for a while. This constructor has been used for a long time. `TimestampFormatter(String format, DateTimeZone timeZone)` is "finally" recommended after some reasonable interval, though.

**Comment by hito4t** [comment]
@hiroyuki-sato @dmikurube 
I think 1 is better because 2 requires a lot of modifications.

@dmikurube 
By the way, it is useful if users can suppress waning messages.

**Comment by dmikurube** [comment]
@hito4t Thanks for your comments.

But this is a deprecation message which means that the constructor is to be removed in the (not very far) future. I'm afraid that suppressing the message can delay plugins' reactions, and users may hit crisis finally when that is removed.

**Comment by hito4t** [comment]
@dmikurube 

Log frameworks can suppress even fatal error messages.

> users may hit crisis finally when that is removed.

Users will upgrade embulk, test, and notice before running it in production environment.

**Comment by hiroyuki-sato** [comment]
@hito4t 

What do you think this change?
https://github.com/hiroyuki-sato/embulk-output-jdbc/commit/c8c07e84f4cab8fba510c8566208842456f9b448

IMO. It breaks backward compatibility. 

When we use this method and keep compatibility, It's a better solution. 
`TimestampFormatter(Task task, Optional<? extends TimestampColumnOption> columnOption)`
But it needs some works

**Comment by dmikurube** [comment]
@hito4t Actually, that is because I didn't use log frameworks there. The message should not be suppressed in our intention. "Fatal messages" are just at that runtime, but this is a long-term compatibility matter.

One misexpectation of ours was that many plugins were using that constructor more than we imagined... Discussing relaxation on the Embulk core side at: https://github.com/embulk/embulk/issues/768

If the core does this, it might be more realistic for the plugin to 1) ignore the messages for a while, and 2) fix this just by removing the first parameter in calling. What do you think?

**Comment by hito4t** [comment]
@hiroyuki-sato @dmikurube 
embulk-output-jdbc should change as https://github.com/hiroyuki-sato/embulk-output-jdbc/commit/c8c07e84f4cab8fba510c8566208842456f9b448 eventually.
But I think it is a bit impetuous because embulk 0.8.29 was released just 1 month ago.
Many users may still use embulk 0.8.28 or older.
Actually, the latest embulk-output-jdbc is built with embulk 0.8.22 .

I think we should apply the change several months later, a few months before embulk removing deprecated constructors.

**Comment by dmikurube** [comment]
@hito4t Thanks! Yeah, that's a good approach. :)  I described the detailed advice (which is like your mention) at: https://github.com/embulk/embulk/issues/745

Jfyi, the way to apply the one of `TimestampColumnOption` is also described in the same issue.
