### ISSUE TITLE
[Feature request] postgresql - Add support for INET data type

### ISSUE THREAD

**Issue by azimut** [embulk/embulk-output-jdbc#201]

**Comment by hito4t** [comment]
I've created the PR #203 .

Although you may already know, you can use INET type with the current embulk-output-postgresql by setting `column_options`.

<pre>
out:
    type: postgresql
    ...
    column_options:
    inet_column: {value_type: string}
</pre>

**Comment by azimut** [comment]
Thanks! I only tried with "type". It worked with the proposed workaround.

**Comment by hito4t** [comment]
That's great!
