### ISSUE TITLE
Enable SORTKEY in output options

### ISSUE THREAD

**Issue by bcipolli** [embulk/embulk-output-jdbc#207]
Basic use-case would be a simple (non-compound) SORTKEY to specify in the output YAML, so that when a table is created, it has a SORTKEY.

**Comment by bcipolli** [comment]
This is specifically for the `REDSHIFT` connector.

**Comment by hito4t** [comment]
@bcipolli 
Hi,
DBMSs have many options for `CREATE TABLE` such as `SORTKEY`, `PRIMARY KEY` (#208), `UNIQUE`, `TABLESPACE`, etc.
If we can add any options for `CREATE TABLE`, users can create any tables.
We need two properties in YML, one is added before last `)` and another is added after last `)`. 
<pre>
CREATE TABLE (
  column1 type1,
  column2 type2,
  ...
  columnN typeN,
  option1 <- we can add PRIMARY KEY
) option2 <- we can add SORTKEY
</pre>

What do you think about this idea?

**Comment by mjalkio** [comment]
`SORTKEY` and `PRIMARY KEY` (for #208) can be specified as part of the `type` in `column_options`.

I believe that you're restricted to non-compound keys (definitely for primary keys, the Redshift documentation is less clear about sort keys) using this method, but it accomplishes the basic use case 😄

**Comment by hito4t** [comment]
I've created the PR #216  !

**Comment by hito4t** [comment]
I've merged the PR and released the new version!
