### ISSUE TITLE
Specify primary key

### ISSUE THREAD

**Issue by bcipolli** [embulk/embulk-output-jdbc#208]
Another `CREATE TABLE` DDL statement that would be helpful is if we could specify a primary key column on the output table.

For a v1, this would only get used if embulk creates the table, otherwise it would be ignored.
For a v2, embulk could `ALTER TABLE` to set the primary key, or query system tables to check and warn/error if the specified primary key column is not the actual primary key.

**Comment by hito4t** [comment]
I've created the PR #216  !

**Comment by bcipolli** [comment]
Thank you @hito4t !

**Comment by hito4t** [comment]
I've merged the PR and released the new version!
