### ISSUE TITLE
Add option not to delete embulk-output-redshift temporary files on S3

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk-output-jdbc#215]
There is a demand to use the temporary files for another use.

**Comment by hiruandon** [comment]
Thank you for creating Issue.

Use Case

1. I used the S3 temporary file as a backup file when Redshift was broken.
1. After that, it is now used to search at Amazon Athena.

If you have the option to not delete S3 temporary file, I am glad.

**Comment by hito4t** [comment]
@hiruandon 
I've created the PR #220.

> If possible, consider the option to set the extension of S3 temporary file to gz.

It maybe useful, but I think it is beyond the scope of embulk-output-redshift.

**Comment by hiruandon** [comment]
@hito4t 

> It maybe useful, but I think it is beyond the scope of embulk-output-redshift.

Yes, I think so too.
A batch program that adds gz extension solved it.

**Comment by hito4t** [comment]
@hiruandon 
I've merged the PR and released the new version!

**Comment by hiruandon** [comment]
@hito4t 
It is an option I wanted!
There was no problem checking my system operation.
Thank you for releasing!
