### ISSUE TITLE
redshift can't insert \r\n and \t data.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-output-jdbc#230]
Reported-by: motikan2010 Thank you!

[【Embulk】MySQL から Redshift へのレコードコピーで「改行&タブが消える」](http://blog.motikan2010.com/entry/2018/04/07/【Embulk】MySQLからRedshiftへのコピーで「改行・タブが消える)

**Comment by hiroyuki-sato** [comment]
@hito4t Can you take a look this issue. 
I made test code. https://github.com/hiroyuki-sato/embulk-support/tree/master/output-jdbc_230_insert_tab
But I don't have Redshift test environment. It seems that this issue Redshift specific issue.
I tested it in PostgreSQL environment. It worked correctly.

**Comment by hito4t** [comment]
@hiroyuki-sato 
Thank you for reporting issue!
I've read the issue, but not tested yet.
I'll test within this week.

**Comment by hito4t** [comment]
@hiroyuki-sato 
I've tried.
The tab character and the new line characters were not inserted correctly into Redshift.
They were inserted correctly into PostgreSQL.

Redshift and PostgreSQL are different in escape specification for COPY.
https://www.postgresql.org/docs/9.4/static/sql-copy.html
https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-conversion.html#copy-escape

**Comment by hiroyuki-sato** [comment]
@hito4t Thank you for investigating the issue!
