### ISSUE TITLE
[PostgreSQL] can't get schema data correctly if column is `character(8)[]`.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-output-jdbc#232]
Follow-up https://github.com/embulk/embulk-input-jdbc/issues/142

* embulk-output-postgresql (0.8.0)

embulk-ouput-postgresql plugin can't create intermediate table if the destination table schema like follows.

```
\d meisai
                  Table "public.meisai"
    Column     |            Type             | Modifiers
---------------+-----------------------------+-----------
 version_id    | smallint                    |
 version       | character(4)                |
 shouhin_id    | character(8)[]              |
 pg_created_at | timestamp without time zone |
 pg_updated_at | timestamp without time zone |
```

The plugin tries to create an intermediate table with the following SQL

```sql
CREATE TABLE "public"."meisai_00000163cfdc3c70_embulk003" (
  "version_id" INT2,
  "version" BPCHAR,
  "shouhin_id" _BPCHAR,
  "pg_created_at" TIMESTAMP,
  "pg_updated_at" TIMESTAMP
)
```

And raise the following exception

```
org.embulk.exec.PartialExecutionException: java.lang.UnsupportedOperationException: Unsupported type _BPCHAR (sqlType=2003, size=8, scale=0)
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:339)
```

It seems that plugin can't get correct data if the column is `character(8)[]`.

**Comment by hiroyuki-sato** [comment]
The cause is that `Type.ARRAY`(`character(8)[]`) doesn't support yet. 
https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/setter/ColumnSetterFactory.java#L178-L188

**Comment by hito4t** [comment]
@hiroyuki-sato @morihaya
Would you try `string` as `value_type`?

<pre>
in:
  ...
  column_options:
    shouhin_id: {type: string}
out:
  ...
  column_options:
    shouhin_id: {value_type: string}
</pre>

**Comment by morihaya** [comment]
You are amazing guy @hito4t !!
It works perfect!!
Than you so mach!

But why dose it work correct ?
I could not find your configuration although read document.

**Comment by hito4t** [comment]
@morihaya 
By `{type: string}` embulk-input-jdbc will get string values from an array type column (that means PostgreSQL will convert array values to string values).

By `{value_type: string}`, embulk-output-jdbc will insert string values into an array type column (that means PostgreSQL will convert string values to array values).

PostgreSQL can convert array values and string values correctly.

**Comment by hiroyuki-sato** [comment]
@hito4t Thank you!.
