### ISSUE TITLE
[mssql] bulk-insert fails with string data longer than 8000

### ISSUE THREAD

**Issue by nickolay** [embulk/embulk-output-jdbc#234]
I got this error:

    [ERROR] (embulk-output-executor-0): SQL Server Native Client : bcp_bind failed (sql state = HY000) : [Microsoft][SQL Server Native Client 11.0]Invalid field size for datatype

Using configuration like the following:

    out:
        type: sqlserver
        driver_path: path\to\mssql-jdbc-7.0.0.jre8.jar
        host: host
        user: user
        password: pass
        database: "..."
        table: table
        mode: insert_direct
        insert_method: native

on a row with a string about ~9000 characters long.

I managed to fix this locally using the idea from [this stackoverflow post](https://stackoverflow.com/questions/25482325/bcp-bind-fails-when-used-with-size-over-8000-bytes-for-varbinarymax-column):

https://github.com/embulk/embulk-output-jdbc/compare/master...nickolay:mssql-bulk-insert-long-text?expand=1

1) Added this to NativeClient.java:

        short bcp_collen(Pointer hdbc, int cbData, int idxServerCol);

2) Patched `public int bindValue(int columnIndex, String value)` in NativeClientWrapper.java:

          checkBCPResult("bcp_bind", client.bcp_bind(
                  odbcHandle,
                  pointer,
                  0,
        -         size
        +         size > 7999 ? 7999 : size,
                  null,
                  0,
                  NativeClient.SQLCHARACTER,
                  columnIndex));

        +   checkBCPResult("bcp_collen", client.bcp_collen(odbcHandle, size, columnIndex));

3) Built with `gradlew gem` from the working directory root

4) Uninstalled the official version of the plugin and ran my own version using:

        ./embulk.bat gem uninstall embulk-output-sqlserver
        ./embulk.bat run -L embulk-output-jdbc/embulk-output-sqlserver config.yml

I don't think I'll have the bandwidth to make a proper PR and I'm not sure this is the correct fix, but I wanted share it anyway in case it helps someone.

**Comment by hito4t** [comment]
Thank you for the very useful information!
I'll try your suggestion!

**Comment by hito4t** [comment]
@nickolay 
I've created the PR #235 !

**Comment by nickolay** [comment]
Works fine for me, thanks!

**Comment by nickolay** [comment]
@hito4t don't mean to nag you, but did you forget to merge the PR (#235) or is it waiting for something?

**Comment by hito4t** [comment]
@nickolay 
Thank you for letting me know!
I've merged.

**Comment by nickolay** [comment]
Excellent, thank you!
