### ISSUE TITLE
embulk-output-jdbc.jar for developing 3rd party plugin

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-output-jdbc#237]
@hito4t 

What do you think to publish embulk-output-jdbc.jar to bintray for developing 3rd party plugin?
Reference: https://github.com/embulk/embulk/issues/1036#issuecomment-431079635

@kulmam92
If you want to use embulk-output-jdbc for developing Snowflake plugin,
Could you comment about your plan?

**Comment by hito4t** [comment]
@hiroyuki-sato
@kulmam92
I've published to bintray!

**Comment by hiroyuki-sato** [comment]
@hito4t Thank you!.
I found https://bintray.com/embulk-output-jdbc/
