### ISSUE TITLE
Couldn't create temporary table correctly if table name length is too long

### ISSUE THREAD

**Issue by kakusuke** [embulk/embulk-output-jdbc#24]
I met this problem at postgresql.
If table name length is longer than 23 bytes, temporary table name is truncated.

I have two idea to solve this problem:

1. move `OracleOutputPlugin#generateSwapTableName` to `AbstractOutputPlugin` and use it at `PostgreSQLOutputPlugin`.
    (But there is a problem: this method looks like to measure length, but postgresql should measure "bytes long"... Multi-byte table name may cause problem.)
2. create unique temporary table name which is fixed length without original table name.

What do you think about it?

**Comment by hito4t** [comment]
Thank you for your suggestion.

Moving OracleOutputPlugin#generateSwapTableName method to the super class is originally TODO, so I think the first idea is better.

As you pointed out, we should measure table name length in bytes in Oracle same as Postgresql.
So generateSwapTableName method needs a charset as a parameter.

In Oracle, we can get a charset by a certain SQL, and it is already implemented as OracleOutputConnection#getCharset method.

So I think following changes are needed.
(1) add JdbcOutputConnection parameter to AbstractJdbcOutputPlugin#generateSwapTableName method.
(2) move OracleOutputPlugin#generateSwapTableName method to AbstractJdbcOutputPlugin class and add java.nio.charset.Charset parameter to it.

Do they work for Postgress?

**Comment by kakusuke** [comment]
It sounds good to me for PostgreSQL, but some database like MySQL have identifier, which is measured by character length.
http://dev.mysql.com/doc/refman/5.0/en/identifiers.html

In my sense, to call `generateSwapTableName(task, ASCII)` for counting up table name characters is a bit strange. 

Why don't you create abstract method like `getLengthAsIdentifier` on `AbstractJdbcOutputPlugin`, and use in generateSwapTableName?

**Comment by hito4t** [comment]
Thank you for your suggestion.

Both max table name length and the way to measure table name length vary by DBMSs, but I think it's better if subclasses should override only one method.

How about this implementation?
https://github.com/embulk/embulk-output-jdbc/compare/master...hito4t:generate-swap-table-name

AbstractJdbcOutputPlugin defines method which takes a table name (and JdbcOutputConnection) and returns whether the table name is valid, and subclasses override the method.

**Comment by kakusuke** [comment]
+1

Thank you!

**Comment by hito4t** [comment]
The implementation above has been merged ( #30 ).
