### ISSUE TITLE
Some records will be lost during retrying in MySQL

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk-output-jdbc#241]
embulk-output-jdbc uses `PreparedStatement#executeBatch` for inserting records, and call the method again when failed to insert records (for example, because of deadlock).

But it seems that MySQL JDBC driver doesn't retain the SQL that causes the error.
So the record will be not inserted even if retried.
<pre>
Connection conn = DriverManager.getConnection(...);
conn.setAutoCommit(false);

Statement statement1 = conn.createStatement();
Statement statement2 = conn.createStatement();

statement1.execute("INSERT INTO test VALUES(3, 899)");
conn.commit();

statement2.addBatch("INSERT INTO test VALUES(1, 11)");
statement2.addBatch("INSERT INTO test VALUES(2, 22)");
statement2.addBatch("INSERT INTO test VALUES(3, 33)"); // causes an exception because of duplicate key
statement2.addBatch("INSERT INTO test VALUES(4, 44)");
try {
    statement2.executeBatch();

} catch (Exception e) {
    e.printStackTrace();
    statement1.execute("DELETE FROM test WHERE pk = 3");
    statement2.executeBatch(); // record1, record2 and record4 will be inserted but recored3 won't be inserted
}
conn.commit();
</pre>

Other JDBC drivers might have same problem.

**Comment by abicky** [comment]
I'm also facing this issue. I've created reproducible codes in https://github.com/abicky/embulk-output-jdbc-issue-241.

**Comment by hito4t** [comment]
@abicky 
Thank you for the information!
I'll try to fix the problem.

**Comment by hito4t** [comment]
The same problem occurred in SQL Server, Oracle and PostgreSQL.
The issue is not MySQL specific.

**Comment by hito4t** [comment]
The PR #251 will fix this issue.

**Comment by abicky** [comment]
Great! I'm not good at Java, but it looks good to me!
We curretly use small `batch_size` and `max_threads` to avoid deadlocks and set `retry_limit` to 0 to retry whole embulk jobs on failure, but our embulk jobs sometimes fails exceeding the retry limit of our task manager.
This patch so helps us. Thank you so much!
