### ISSUE TITLE
[Redshift]support COPY and UNLOAD via IAM Role.

### ISSUE THREAD

**Issue by ynishi** [embulk/embulk-output-jdbc#260]
AWS Redshift supports that copy and unload via credential iam-role.
https://docs.aws.amazon.com/redshift/latest/mgmt/copy-unload-iam-role.html

It is needed to specify iam-role identity explicitly in query like,
https://docs.aws.amazon.com/ja_jp/redshift/latest/dg/r_COPY.html
```
copy catdemo
from 's3://awssampledbuswest2/tickit/category_pipe.txt'
iam_role 'arn:aws:iam::<aws-account-id>:role/<role-name>'
region 'us-west-2';
```
https://docs.aws.amazon.com/redshift/latest/dg/copy-usage_notes-access-permissions.html
```
copy customer from 's3://mybucket/mydata' 
credentials 
'aws_iam_role=arn:aws:iam::0123456789012:role/MyRedshiftRole';
```

It looks not support it,
https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-redshift/src/main/java/org/embulk/output/redshift/RedshiftCopyBatchInsert.java#L307-L315

If it is not supported, how about support it, for example add optional task arg iamCopyUnloadRoleName.

**Comment by ynishi** [comment]
This is WIP, build successful, but not test credential code.
https://github.com/embulk/embulk-output-jdbc/compare/master...ynishi:redshift_copy_unload_iam_role?expand=1#diff-ac17d42cee00b84f05a3f148479a457a

**Comment by hito4t** [comment]
@ynishi 
Thank you for your suggestion!
We should use IAM role rather than access key and secret key for security reason.

Can you create a pull request based on the above code?

**Comment by ynishi** [comment]
Thank you for reply so quick!
Yes, of course, I'm going to test code and create pull request.

**Comment by ynishi** [comment]
I'd checked behavior, my local environment like below, and dump query.
```
./gradlew gem
embulk run -I embulk-output-jdbc/embulk-output-redshift/lib/ config.yml
```
It looks working when auth(iam, instance...) success or fail, and iam_role is set or not.
And, I added account ID option for support multi account.

**Comment by ynishi** [comment]
Thanks to merge!
I close.
