### ISSUE TITLE
Upgrade gradle?

### ISSUE THREAD

**Issue by nickolay** [embulk/embulk-output-jdbc#265]
I don't normally develop in Java, so getting a dev environment set up took 90% of the time it took to create #264.

In particular, when I tried to open the project (the root `build.gradle` file) from this repo in IntelliJ IDEA Community 2019.2.3, and got two subsequent messages asking me to upgrade gradle:

* Support for builds using Gradle versions older than 2.6 was removed in tooling API version 5.0
* The project uses Gradle 2.6 which is incompatible with IDEA running on Java 10 or newer.

Upgrading it to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.8.1-all.zip` seems to work, any reason this can't be committed in the repo? 

By the way, how can I quickly test a change in the plugin? https://www.embulk.org/docs/customization.html#step-2-building-the-project only mentions `./gradlew package` which doesn't work in this repo. I use `./gradlew gem`, but it takes two minutes to run...

**Comment by hiroyuki-sato** [comment]
Hello, @nickolay 

Embulk require Java 8. And it doesn't support Java 9 and above yet.

Have you ever tried to execute `./gradlew check` for testing plugin?

**Comment by nickolay** [comment]
Hi @hiroyuki-sato, thanks for your reply!

> Embulk require Java 8. And it doesn't support Java 9 and above yet.

Yes, I recall reading about this, so I only had JDK 8 installed when I tested the newer gradle (which [claims to still support Java 8](https://docs.gradle.org/current/userguide/installation.html)).

If you mention this because of the second message about IDEA running on Java 10, I didn't think this was a problem - the IDE can run on its own, newer JRE, cannot it?

>Have you ever tried to execute ./gradlew check for testing plugin?

Thanks, I tried it now. It still takes a minute on my laptop and it doesn't generate the gem, so `embulk` doesn't pick up my code when I run it with `-L path\to\embulk-output-jdbc\embulk-output-sqlserver` as [recommended in the dev docs](https://www.embulk.org/docs/customization.html#step-3-confirm-it-works). Am I missing something?

**Comment by hiroyuki-sato** [comment]
Hello, @nickolay 

Please try `./gradlew gem` if you want to  for generating gem.
It will generate gem package in pkg directory.

If you want to test your modification. execute like the below.

```
./gradlew package
embulk run -I embulk-output-sqlserver/lib/ config.yml
```

You can find more detail in [Embulk Input Plugin Development Guide](https://docs.google.com/document/d/1oKpvgstKlgmgUUja8hYqTqWxtwsgIbONoUaEj8lO0FE/edit)

**Comment by nickolay** [comment]
> You can find more detail in Embulk Input Plugin Development Guide

Oh, thanks! I have totally missed that link [on the embulk.org homepage](https://www.embulk.org/docs/#for-developers) because it was outside of the "Customization" page. I'll try that this weekend!

Do you think gradle can be updated in this repo? If not, let's close this issue.

**Comment by hiroyuki-sato** [comment]
Hello, @nickolay 

I'm not sure about gradle 5.X. but gradle 4.X may work well.
The following command update gradle to 4.1.
I don't have any concern about this 
@hito4t What do you think to update gradle?

```
cd embulk-output-jdbc
embulk migrate .
```

**Comment by hiroyuki-sato** [comment]
Gradle updated to 5.0 (It will update to 6.X later)

**Comment by nickolay** [comment]
Thanks! I guess there's no point in keeping this issue open then?

**Comment by hiroyuki-sato** [comment]
@nickolay Thanks! Due to I'm not maintainer, I couldn't close this issue
