### ISSUE TITLE
cannot an insert statement after executing an update statement with after_load of embulk, 

### ISSUE THREAD

**Issue by koichi-oshima** [embulk/embulk-output-jdbc#298]
I want to execute an insert statement after executing an update statement with after_load of embulk, but the following code causes a syntax error.

If you know how to do it, please let me know.

## Code

```
{% include'input'%}
  table: tableA
{% include'output'%}
  table: tableA
  after_load: update XX;
              insert XX;
```

## Error
```
Error: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near'update XXX' at line 1
```

**Comment by hiroyuki-sato** [comment]
As I [commented before](https://github.com/embulk/embulk-input-jdbc/issues/219#issuecomment-862382541), I recommend you to use a Stored Procedure. IIUC, `after_load` doesn't support multiple SQL statements.

**Comment by koichi-oshima** [comment]
thank you for your answer.
Sorry for the lack of confirmation.
