### ISSUE TITLE
how to load incremental data from oracle to oracle

### ISSUE THREAD

**Issue by yester354** [embulk/embulk-output-jdbc#59]
Hi
    in my environment.I want to load the increamental data from oracle to oracle.for example 
in host a.it has a table test and has one row.after i finish loading data from host a to host b.the table test in host a has anthoer new data and it has two row. i want to load only the new data to host b .

**Comment by hito4t** [comment]
Hi
You can use `mode: insert_direct` for incremental load.

**Comment by frsyuki** [comment]
You run embulk command periodically (like every day)?
An idea in my mind is to supporting `last_record` variable in query: parameter of embulk-*input*-jdbc like this:

```
in:
  type: oracle
  ...
  query: |
    SELECT id, name, created_at
    FROM table1
    WHERE created_at > ${last_record created_at}
    ORDER BY created_at
last_record:
  id: 10
  name: "abc"
  created_at: "2015-01-01 00:00:00"
```

`last_record` is updated by ConfigDiff.  But this is not implemented.

Workaround for now is generating config file every time using Liquid template engine like this:

config:

```
in:
  type: oracle
  ...
  query: |
    SELECT id, name, created_at
    FROM table1
    WHERE created_at > timestamp '{{env.last_created_at}}'
    ORDER BY created_at
```

command:

```
$ export last_created_at="2015-01-01 00:00:00"
$ embulk config.yml
```

**Comment by yester354** [comment]
@hito4t 
  Hi,i tried the mode insert_direct .it doesnt works .the target table always has more datas than source table

**Comment by yester354** [comment]
@frsyuki 
  Hi .i make a crontab to run embulk hourly.now i use a very complex way to get what i want.
i create a table in my database to record the last insert time as below
#!/bin/sh
a=`su - oracle -c 'sqlplus -s / as sysdba<<EOF
set heading off
select max(bigdate)  from lastupd;
EOF'`
if [ -z $a ];then 
su - oracle -c 'sqlplus -s / as sysdba<<EOF 
set heading off
insert into lastupd (bigdate) select max(indate) from sync.ac;
commit;
EOF'
echo "in:
  type: oracle
  driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
  host: 10.89.13.56
  user: sync
  password: m123
  database: oggmysql
  query: |
    select * from sync.ac where indate<=(select max(bigdate) from sys.lastupd)
out:
  type: oracle
  driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
  host: 10.89.13.57
  user: flume
  password: m123
  database: embulk
  table: AC
  mode: insert
  insert_method: normal
  column_options:
               OWNER: {type: VARCHAR2(30)}
               OBJECT_NAME: {type: VARCHAR2(128)}
               SUBOBJECT_NAME: {type: VARCHAR2(30)}
               OBJECT_ID: {type: NUMBER}
               DATA_OBJECT_ID: {type: NUMBER}
               OBJECT_TYPE: {type: VARCHAR2(19)}
               CREATED: {type: DATE}
               LAST_DDL_TIME: {type: DATE}
               TIMESTAMP: {type: VARCHAR2(19)}
               STATUS: {type: VARCHAR2(7)}
               TEMPORARY: {type: VARCHAR2(1)}
               GENERATED: {type: VARCHAR2(1)}
               SECONDARY: {type: VARCHAR2(1)}
               NAMESPACE: {type: NUMBER}
               EDITION_NAME: {type: VARCHAR2(30)} ">/tmp/sync.yml
embulk run /tmp/sync.yml>>/opt/embulkrun.log
else
su - oracle -c "sqlplus -s / as sysdba<<EOF
set heading off
set serveroutput on
set feedback off
alter session set nls_date_format='yyyymmdd hh24:mi:ss';
spool /tmp/1.log
declare
a date;
b date;
begin
select max(indate) into a from sync.ac;
select max(bigdate) into b from sys.lastupd;
if a=b then
dbms_output.put_line(0);
else
insert into lastupd (bigdate) select max(indate) from sync.ac;
commit;
dbms_output.put_line(1);
end if;
end;
/
spool off
exit
EOF"
a=`cat /tmp/1.log`
if [ $a -eq  1 ] ;then
echo "in:
  type: oracle
  driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
  host: 10.89.13.56
  user: sync
  password: m123
  database: oggmysql
  query: |
    select * from sync.ac where indate<=(select max(bigdate) from sys.lastupd) and indate > (select lastmax  from (select bigdate,lag(bigdate） over (order by bigdate) lastmax from sys.lastupd) where bigdate>=(select max(bigdate) from sys.lastupd))
out:
  type: oracle
  driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
  host: 10.89.13.57
  user: flume
  password: m123
  database: embulk
  table: AC
  mode: insert
  insert_method: normal
  column_options:
               OWNER: {type: VARCHAR2(30)}
               OBJECT_NAME: {type: VARCHAR2(128)}
               SUBOBJECT_NAME: {type: VARCHAR2(30)}
               OBJECT_ID: {type: NUMBER}
               DATA_OBJECT_ID: {type: NUMBER}
               OBJECT_TYPE: {type: VARCHAR2(19)}
               CREATED: {type: DATE}
               LAST_DDL_TIME: {type: DATE}
               TIMESTAMP: {type: VARCHAR2(19)}
               STATUS: {type: VARCHAR2(7)}
               TEMPORARY: {type: VARCHAR2(1)}
               GENERATED: {type: VARCHAR2(1)}
               SECONDARY: {type: VARCHAR2(1)}
               NAMESPACE: {type: NUMBER}
               EDITION_NAME: {type: VARCHAR2(30)} " >/tmp/sync.yml
embulk run /tmp/sync.yml>>/opt/embulkrun.log
else 
echo ''>/tmp/sync.yml
fi
fi

my method is too complex .i will try the method you provided.i want make it sample

**Comment by frsyuki** [comment]
ok. it seems that you anyways need some scripting.

**Comment by hito4t** [comment]
HI
I'm sorry, my answer is wrong.
embulk-output-oracle doesn't support incremental loading.

**Comment by yester354** [comment]
@hito4t 
thanks all the way!

**Comment by yester354** [comment]
@frsyuki 
yes.i make a script to run embulk.but indeed i weak at scripting .and i am afraid that the script won't works well  in complex environment.
