### ISSUE TITLE
merge mode is not supported in embulk-output-redshift

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk-output-jdbc#72]
README and Features#getSupportedModes say that embulk-output-redshift supports merge mode, but it is not implemented actually.

**Comment by hito4t** [comment]
I've tried to merge in Redshift in the same way as embulk-output-postgresql, but following error occured.
<pre>
2015-12-17 18:11:10.612 +0900 [INFO] (transaction): SQL: WITH updated AS (UPDATE "test_table" SET "id" = S."id", ...
...
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "UPDATE"
  Position: 18
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:363)
</pre>

It seems that `WITH ... UPDATE` is supported in PostgreSQL,
http://www.postgresql.org/docs/9.4/interactive/sql-update.html
but not supported in Redshift.
http://docs.aws.amazon.com/redshift/latest/dg/r_UPDATE.html

**Comment by xinuc** [comment]
is it possible to implement merge for redshift?

**Comment by hito4t** [comment]
It is not impossible.

embulk-output-jdbc merges each record by 1 SQL statement.
It is fast, but depends on DBMS-specific SQL.
And redshift doesn't support such SQL.

With standard SQL, we should execute as follows.
- update record
- check result
- if not updated, insert record

It will be very slow, but doesn't depend on DBMS.

**Comment by xinuc** [comment]
https://github.com/embulk/embulk-output-jdbc/pull/105
@hito4t @frsyuki

**Comment by yaningzhu** [comment]
Hi! Thanks for including the fix in 0.6.1. Do you have a rough timeline when that's going to be released?

**Comment by hito4t** [comment]
I'll release v 0.6.1 in this week after merging #108 !
