### ISSUE TITLE
Partial delete option before insert/merge

### ISSUE THREAD

**Issue by ghost** [embulk/embulk-output-jdbc#89]
Here's the use case: doing an incremental update of all the records that changed on day X. embulk-output-jdbc supports this now, except that it is not idempotent. If we want to reload old data cleanly, we have to do manual DELETEs. It seems like to support incremental updates in an idempotent way, the plugin should run a "DELETE ... WHERE ..." clause before the insert or merge phase. 

output:
  type: jdbc
   ...
  delete_where: modified_date between {{ env.date1 }} and {{ env.date2 }}

Why not just do a DELETE in advance? We do this in our old software. One argument is that the DELETE should be part of the transaction that supplies the new records.

If I post this are you folks interested? I don't have the facilities to test this on all of the supported DBs. I'll be testing on MySQL and Redshift.

**Comment by frsyuki** [comment]
this idea sounds good.

**Comment by hito4t** [comment]
I think so too.

It should be more useful if we can execute any SQL (not only `DELETE`, but also `TRUNCATE`, `UPDATE`, ...) before loading.

Thanks
