### ISSUE TITLE
embulk-output-postgresql: document merge_keys

### ISSUE THREAD

**Issue by strife25** [embulk/embulk-output-jdbc#90]
When using `mode: merge`, an error gets displayed asking one to set the `merge_keys` in the configuration file. 

Although it is easy to guess what it does, this parameter is not documented and may confuse users.

**Comment by hito4t** [comment]
Thank you for the comment!

I'll update the README soon.

**Comment by hito4t** [comment]
Please see https://github.com/embulk/embulk-output-jdbc/pull/91 .
